<?xml version="1.0" encoding="UTF-8"?><testrun name="NovelExceptionsTest" project="backend" tests="6" started="6" failures="1" errors="0" ignored="0">
  <testsuite name="com.novelsbr.backend.exceptions.NovelExceptionsTest" time="4.206" displayname="NovelExceptionsTest" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.exceptions.NovelExceptionsTest]">
    <testcase name="preparingTestEnvironment" classname="com.novelsbr.backend.exceptions.NovelExceptionsTest" time="3.836" displayname="preparingTestEnvironment()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.exceptions.NovelExceptionsTest]/[method:preparingTestEnvironment()]"/>
    <testcase name="nullEntityException_With_NovelNull" classname="com.novelsbr.backend.exceptions.NovelExceptionsTest" time="0.022" displayname="nullEntityException_With_NovelNull()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.exceptions.NovelExceptionsTest]/[method:nullEntityException_With_NovelNull()]"/>
    <testcase name="novelNotFound_WithIdNonexistent" classname="com.novelsbr.backend.exceptions.NovelExceptionsTest" time="0.02" displayname="novelNotFound_WithIdNonexistent()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.exceptions.NovelExceptionsTest]/[method:novelNotFound_WithIdNonexistent()]"/>
    <testcase name="existingNovelException_With_existingNovelName" classname="com.novelsbr.backend.exceptions.NovelExceptionsTest" time="0.074" displayname="existingNovelException_With_existingNovelName()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.exceptions.NovelExceptionsTest]/[method:existingNovelException_With_existingNovelName()]"/>
    <testcase name="nullEntityException_With_authorNull" classname="com.novelsbr.backend.exceptions.NovelExceptionsTest" time="0.146" displayname="nullEntityException_With_authorNull()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.exceptions.NovelExceptionsTest]/[method:nullEntityException_With_authorNull()]">
      <failure>
        <expected>class com.novelsbr.backend.exceptions.NullEntityException</expected>
        <actual>class java.lang.NullPointerException</actual>
        org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;com.novelsbr.backend.exceptions.NullEntityException&gt; but was: &lt;java.lang.NullPointerException&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)&#13;
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)&#13;
	at com.novelsbr.backend.exceptions.NovelExceptionsTest.nullEntityException_With_authorNull(NovelExceptionsTest.java:121)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
Caused by: java.lang.NullPointerException: Cannot invoke "com.novelsbr.backend.domain.entities.Author.getId()" because the return value of "com.novelsbr.backend.domain.entities.Novel.getAuthor()" is null&#13;
	at com.novelsbr.backend.domain.dto.NovelDTO.&lt;init&gt;(NovelDTO.java:36)&#13;
	at com.novelsbr.backend.exceptions.NovelExceptionsTest.lambda$4(NovelExceptionsTest.java:121)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)&#13;
	... 6 more&#13;
&#13;

      </failure>
    </testcase>
    <testcase name="novelInfoNotFound_WithIdNonexistent" classname="com.novelsbr.backend.exceptions.NovelExceptionsTest" time="0.082" displayname="novelInfoNotFound_WithIdNonexistent()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.exceptions.NovelExceptionsTest]/[method:novelInfoNotFound_WithIdNonexistent()]"/>
  </testsuite>
</testrun>
